### PR TITLE
Puppeteer

### PR DESCRIPTION
**Pull request by bung87**
using [looks-same](https://www.npmjs.com/package/looks-same) instead of [image-diff](https://www.npmjs.com/package/image-diff) as it no longer maitained
replace 3 expected images passing test.

### CODE REVIEW

**Comment by mojoaxel** [comment]
@bung87 Thank you so much for helping with this!
> using looks-same instead of image-diff as it no longer maitained

This improvement I can merge without hesitation! Thanks

> replace 3 expected images passing test.

You updated the following test-images:
- test/expected/png/css.horizontal.mixed.png
- test/expected/png/css.packed.png

The problem with this is that this branch should be merged into the official implementation (https://github.com/jkphl/svg-sprite/pull/284).
That tests fail means that my/our new implementation is not fully compatible with the existing version.

**This issue needs some more looking into to not break something for users!**

I'm going to cherry pick your update without the images changes and talk to the svg-sprite maintainers how we can go on with this.

Thanks again!! :+1: 
Your PR gave me a new chance to work on this!

**Comment by bung87** [comment]
yeah, you're right, the hard parts need more carefully deep into, as I have no idea what make these images differient and how to solve it, I just leave it as is.

**Comment by mojoaxel** [comment]
@bung87 I've added your contributions.  :+1: 
Please feel free to support me in the process of getting https://github.com/jkphl/svg-sprite/pull/284 merged :wink:

**Comment by mojoaxel** [comment]
partially merged with https://github.com/mojoaxel/svg-sprite/commit/268a857992a96d8cf3d3044abb5a3ae22fd06351

**Pull request closed without merging**
